<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:extns="http://schema.tibco.com/schema/product" xmlns:tns="http://service.tibco.com/product/wsdl/1502044858829" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Product_Resource_SOAP" targetNamespace="http://service.tibco.com/product/wsdl/1502044858829">
  <wsdl:import namespace="http://schema.tibco.com/schema/product"/>
  <wsdl:message name="getProductRequest">
    <wsdl:part element="extns:getProductRequest" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="getProductResponse">
    <wsdl:part element="extns:getProductResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="getProductFault">
    <wsdl:part element="extns:getProductFault" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="Product_Resource_SOAP">
    <wsdl:operation name="getProduct">
      <wsdl:input message="tns:getProductRequest" name="getProductInput"/>
      <wsdl:output message="tns:getProductResponse" name="getProductOutput"/>
      <wsdl:fault message="tns:getProductFault" name="Fault"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
